version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/code
      - ./media:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - DEBUG=1
    env_file:
      - .env

  mongodb:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
