# Generated by Django 5.2.4 on 2025-07-13 20:52

import cruise_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_app', '0002_remove_crewimage_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id_number', models.CharField(max_length=20, unique=True, validators=[cruise_app.models.validate_crew_id_number])),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height_m', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('hair_color', models.CharField(max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=2)),
                ('position', models.CharField(max_length=50)),
                ('crew_id_expire', models.CharField(max_length=10)),
                ('address_philippines', models.CharField(max_length=200)),
                ('address_usa', models.CharField(max_length=200)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('arrival_mode', models.CharField(max_length=50)),
                ('cbp_permit_expire', models.DateField()),
                ('ship', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='crewimage',
            name='crew_id_number',
        ),
        migrations.AddField(
            model_name='crewimage',
            name='image_type',
            field=models.CharField(default='ID_CARD_FRONT', max_length=50),
        ),
        migrations.AlterField(
            model_name='crewimage',
            name='image',
            field=models.ImageField(upload_to='idcards/'),
        ),
        migrations.AlterField(
            model_name='crewimage',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='crewimage',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cruise_app.person'),
        ),
    ]
