# Generated by Django 5.2.4 on 2025-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_app', '0003_person_remove_crewimage_crew_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
