# Generated by Django 5.2.4 on 2025-07-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_app', '0005_alter_person_address_philippines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='crew_id_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
