# Generated by Django 5.2.4 on 2025-07-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_app', '0006_alter_person_crew_id_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.CharField(max_length=64),
        ),
    ]
